export const ALL_MODULES = [
  // ── Pure Mathematics — Algebra ──────────────────────────────────────
  {
    id: "polynomials",
    title: "Polynomials",
    description: "Study of polynomial expressions, their roots, factorization, and algebraic properties.",
    author: "Prof. Dupont",
    color: "#6366f1",
    icon: "function",
    code: "ALG.1",
    category: "Pure Mathematics — Algebra",
    motivation:
      "Polynomials are the simplest non-trivial objects in all of algebra, yet they encode an astonishing depth of structure. From solving quadratic equations in ancient Babylon to modern error-correcting codes, polynomials appear everywhere. Master them and you hold the master key to the rest of algebra.",
    bibliography: JSON.stringify([
      { title: "Polynomials", author: "Victor V. Prasolov", level: "intermediate" },
      { title: "Algebra", author: "Michael Artin", level: "intermediate" },
      { title: "Abstract Algebra", author: "David S. Dummit, Richard M. Foote", level: "advanced" },
      { title: "Precalculus Mathematics in a Nutshell", author: "George F. Simmons", level: "intro" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },
  {
    id: "linear-algebra",
    title: "Linear Algebra",
    description: "Theory of vector spaces, linear transformations, matrices, and eigenvalues.",
    author: "Prof. Bernard",
    color: "#10b981",
    icon: "grid",
    code: "ALG.2",
    category: "Pure Mathematics — Algebra",
    motivation:
      "Linear algebra is the workhorse of modern mathematics. Whether you want to train a neural network, solve a system of differential equations, or understand quantum mechanics, you will need to think in terms of vectors and linear maps. It is the language that unifies an extraordinary range of disciplines.",
    bibliography: JSON.stringify([
      { title: "Linear Algebra Done Right", author: "Sheldon Axler", level: "intermediate" },
      { title: "Introduction to Linear Algebra", author: "Gilbert Strang", level: "intro" },
      { title: "Linear Algebra", author: "Friedberg, Insel, Spence", level: "intermediate" },
      { title: "Advanced Linear Algebra", author: "Steven Roman", level: "advanced" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },
  {
    id: "galois",
    title: "Galois Theory",
    description: "The deep connection between field extensions and group theory that settles the solvability of polynomial equations.",
    author: "Prof. Laurent",
    color: "#f59e0b",
    icon: "star",
    code: "ALG.3",
    category: "Pure Mathematics — Algebra",
    motivation:
      "Galois theory is one of the crown jewels of mathematics. Born from the mind of a twenty-year-old who would die in a duel the very next day, it answers a question humanity had asked for centuries: which polynomial equations can be solved by radicals? The answer reveals a breathtaking interplay between symmetry and structure that reverberates across all of modern algebra.",
    bibliography: JSON.stringify([
      { title: "Galois Theory", author: "Ian Stewart", level: "intermediate" },
      { title: "Fields and Galois Theory", author: "J.S. Milne", level: "intermediate" },
      { title: "Algebra", author: "Serge Lang", level: "advanced" },
      { title: "A Book of Abstract Algebra", author: "Charles C. Pinter", level: "intro" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },
  {
    id: "abstract-algebra",
    title: "Abstract Algebra",
    description: "Groups, rings, fields, and the unifying structures that underpin modern algebra.",
    author: "Prof. Lefèvre",
    color: "#818cf8",
    icon: "layers",
    code: "ALG.4",
    category: "Pure Mathematics — Algebra",
    motivation:
      "Abstract algebra teaches you to see the skeleton beneath the flesh of mathematics. When you realize that integers under addition and rotations of a square obey the same abstract laws, a whole new world opens up. This is the course where mathematics becomes truly modern — and truly powerful.",
    bibliography: JSON.stringify([
      { title: "Algebra: Chapter 0", author: "Paolo Aluffi", level: "advanced" },
      { title: "Abstract Algebra", author: "David S. Dummit, Richard M. Foote", level: "advanced" },
      { title: "A Book of Abstract Algebra", author: "Charles C. Pinter", level: "intro" },
      { title: "Topics in Algebra", author: "I.N. Herstein", level: "intermediate" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Pure Mathematics — Calculus and Analysis ────────────────────────
  {
    id: "real-analysis",
    title: "Real Analysis",
    description: "Rigorous foundations of calculus: limits, continuity, differentiation, and integration on the real line.",
    author: "Prof. Moreau",
    color: "#3b82f6",
    icon: "trending-up",
    code: "ANA.1",
    category: "Pure Mathematics — Calculus and Analysis",
    motivation:
      "You used limits and derivatives in calculus, but did you ever truly understand why they work? Real analysis rebuilds the entire edifice from the ground up, with absolute logical precision. It is a rite of passage that transforms a student who computes into a mathematician who proves.",
    bibliography: JSON.stringify([
      { title: "Principles of Mathematical Analysis", author: "Walter Rudin", level: "intermediate" },
      { title: "Understanding Analysis", author: "Stephen Abbott", level: "intro" },
      { title: "Real Analysis: Modern Techniques and Their Applications", author: "Gerald B. Folland", level: "advanced" },
      { title: "Analysis I", author: "Terence Tao", level: "intermediate" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },
  {
    id: "complex-analysis",
    title: "Complex Analysis",
    description: "Analysis of functions of a complex variable, including contour integration and conformal mappings.",
    author: "Prof. Moreau",
    color: "#60a5fa",
    icon: "compass",
    code: "ANA.2",
    category: "Pure Mathematics — Calculus and Analysis",
    motivation:
      "Complex analysis is often called the most beautiful branch of mathematics, and for good reason. The moment you allow the square root of minus one, calculus becomes almost miraculously well-behaved: differentiable once means differentiable infinitely many times, and integrals around closed loops unlock deep number-theoretic secrets. Prepare to be astonished.",
    bibliography: JSON.stringify([
      { title: "Visual Complex Analysis", author: "Tristan Needham", level: "intro" },
      { title: "Complex Analysis", author: "Lars Ahlfors", level: "intermediate" },
      { title: "Functions of One Complex Variable", author: "John B. Conway", level: "intermediate" },
      { title: "Complex Analysis", author: "Elias M. Stein, Rami Shakarchi", level: "advanced" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },
  {
    id: "functional-analysis",
    title: "Functional Analysis",
    description: "Infinite-dimensional vector spaces, operators, and the analytic backbone of modern physics.",
    author: "Prof. Nguyen",
    color: "#38bdf8",
    icon: "maximize",
    code: "ANA.3",
    category: "Pure Mathematics — Calculus and Analysis",
    motivation:
      "What happens when linear algebra meets analysis in infinite dimensions? You get functional analysis — the framework that makes quantum mechanics rigorous, that powers the modern theory of PDEs, and that provides the abstract setting for signal processing. If you want to do serious applied or pure mathematics, this is indispensable.",
    bibliography: JSON.stringify([
      { title: "Introductory Functional Analysis with Applications", author: "Erwin Kreyszig", level: "intro" },
      { title: "Functional Analysis", author: "Walter Rudin", level: "advanced" },
      { title: "Functional Analysis, Sobolev Spaces and Partial Differential Equations", author: "Haim Brezis", level: "advanced" },
      { title: "A Course in Functional Analysis", author: "John B. Conway", level: "intermediate" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Pure Mathematics — Geometry and Topology ────────────────────────
  {
    id: "euclidean-geometry",
    title: "Euclidean Geometry",
    description: "Classical geometry of points, lines, circles, and transformations in the plane and space.",
    author: "Prof. Mercier",
    color: "#34d399",
    icon: "triangle",
    code: "GEO.1",
    category: "Pure Mathematics — Geometry and Topology",
    motivation:
      "Euclidean geometry is where mathematical proof was born — two thousand years ago, with Euclid's Elements. Far from being an outdated relic, it trains your geometric intuition and your ability to reason rigorously from axioms. Many competition problems and modern results still trace their roots back to the elegance of classical geometry.",
    bibliography: JSON.stringify([
      { title: "Euclidean Geometry in Mathematical Olympiads", author: "Evan Chen", level: "intermediate" },
      { title: "Geometry Revisited", author: "H.S.M. Coxeter, S.L. Greitzer", level: "intermediate" },
      { title: "The Four Pillars of Geometry", author: "John Stillwell", level: "intro" },
      { title: "Euclid's Elements", author: "Euclid (translated by T.L. Heath)", level: "intro" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },
  {
    id: "topology",
    title: "Topology",
    description: "The study of spatial properties preserved under continuous deformations.",
    author: "Prof. Duval",
    color: "#2dd4bf",
    icon: "circle",
    code: "GEO.2",
    category: "Pure Mathematics — Geometry and Topology",
    motivation:
      "Topology asks the question: what properties of a shape survive when you stretch and bend it, but never tear or glue? This deceptively simple idea leads to some of the deepest mathematics of the 20th century. From classifying surfaces to understanding the shape of the universe, topology gives you eyes to see structure that geometry alone cannot reveal.",
    bibliography: JSON.stringify([
      { title: "Topology", author: "James R. Munkres", level: "intermediate" },
      { title: "Introduction to Topological Manifolds", author: "John M. Lee", level: "intermediate" },
      { title: "Algebraic Topology", author: "Allen Hatcher", level: "advanced" },
      { title: "Topology: A Very Short Introduction", author: "Richard Earl", level: "intro" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },
  {
    id: "differential-geometry",
    title: "Differential Geometry",
    description: "Geometry of curves, surfaces, and manifolds studied through calculus and linear algebra.",
    author: "Prof. Petit",
    color: "#a3e635",
    icon: "globe",
    code: "GEO.3",
    category: "Pure Mathematics — Geometry and Topology",
    motivation:
      "Differential geometry is the language of general relativity and gauge theory — it is how we describe the curvature of spacetime itself. But even beyond physics, it offers a gorgeous synthesis of analysis, algebra, and geometry. Learning to think on curved spaces will permanently change how you see the mathematical world.",
    bibliography: JSON.stringify([
      { title: "Differential Geometry of Curves and Surfaces", author: "Manfredo P. do Carmo", level: "intro" },
      { title: "Introduction to Smooth Manifolds", author: "John M. Lee", level: "intermediate" },
      { title: "Riemannian Geometry", author: "Manfredo P. do Carmo", level: "advanced" },
      { title: "Visual Differential Geometry and Forms", author: "Tristan Needham", level: "intermediate" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Pure Mathematics — Combinatorics ────────────────────────────────
  {
    id: "combinatorics",
    title: "Combinatorics",
    description: "The art of counting, arranging, and analyzing discrete structures.",
    author: "Prof. Roche",
    color: "#fb923c",
    icon: "hash",
    code: "COM.1",
    category: "Pure Mathematics — Combinatorics",
    motivation:
      "How many ways can you seat ten guests around a table? How many paths cross a grid? Combinatorics turns these innocent-sounding questions into a rich theory with deep connections to algebra, probability, and computer science. It is the mathematics of choice and arrangement, and it is everywhere — from poker to cryptography to algorithm design.",
    bibliography: JSON.stringify([
      { title: "Combinatorics: Topics, Techniques, Algorithms", author: "Peter J. Cameron", level: "intro" },
      { title: "Enumerative Combinatorics, Vol. 1", author: "Richard P. Stanley", level: "advanced" },
      { title: "A Walk Through Combinatorics", author: "Miklós Bóna", level: "intermediate" },
      { title: "Generatingfunctionology", author: "Herbert S. Wilf", level: "intermediate" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Pure Mathematics — Logic ────────────────────────────────────────
  {
    id: "mathematical-logic",
    title: "Mathematical Logic",
    description: "Formal systems, propositional and predicate logic, completeness, and incompleteness theorems.",
    author: "Prof. Simon",
    color: "#a78bfa",
    icon: "cpu",
    code: "LOG.1",
    category: "Pure Mathematics — Logic",
    motivation:
      "Mathematical logic asks the most fundamental question of all: what can be proved, and what lies forever beyond the reach of proof? From Godel's shattering incompleteness theorems to the foundations of computer science, logic is where mathematics turns its gaze inward and examines its own power and limitations. There is no deeper inquiry.",
    bibliography: JSON.stringify([
      { title: "A Mathematical Introduction to Logic", author: "Herbert B. Enderton", level: "intermediate" },
      { title: "Logic for Mathematicians", author: "A.G. Hamilton", level: "intro" },
      { title: "Godel's Proof", author: "Ernest Nagel, James R. Newman", level: "intro" },
      { title: "Model Theory: An Introduction", author: "David Marker", level: "advanced" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },
  {
    id: "proof-writing",
    title: "How to Write Proofs",
    description: "Techniques and strategies for constructing clear, correct mathematical proofs.",
    author: "MathGraph Team",
    color: "#8b5cf6",
    icon: "pen-tool",
    code: "LOG.2",
    category: "Pure Mathematics — Logic",
    motivation:
      "Proof is the heartbeat of mathematics. Without it, a claim is just a guess. This module teaches you the craft of proof — direct arguments, contradiction, induction, contraposition — so you can move from passively reading mathematics to actively creating it. Every serious mathematics student must master this skill early.",
    bibliography: JSON.stringify([
      { title: "How to Prove It", author: "Daniel J. Velleman", level: "intro" },
      { title: "Book of Proof", author: "Richard Hammack", level: "intro" },
      { title: "How to Solve It", author: "George Polya", level: "intro" },
      { title: "Proofs and Fundamentals", author: "Ethan D. Bloch", level: "intermediate" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Pure Mathematics — Number Theory ────────────────────────────────
  {
    id: "arithmetic",
    title: "Arithmetic",
    description: "Elementary number theory: divisibility, primes, congruences, and Diophantine equations.",
    author: "Prof. Martin",
    color: "#ec4899",
    icon: "hash",
    code: "NUM.1",
    category: "Pure Mathematics — Number Theory",
    motivation:
      "Number theory is the queen of mathematics, as Gauss famously declared. Starting from the humblest objects — the integers — it builds toward some of the most beautiful and difficult open problems in all of science. From the distribution of prime numbers to modern cryptography, arithmetic is both ancient and urgently contemporary.",
    bibliography: JSON.stringify([
      { title: "An Introduction to the Theory of Numbers", author: "G.H. Hardy, E.M. Wright", level: "intermediate" },
      { title: "Elementary Number Theory", author: "David M. Burton", level: "intro" },
      { title: "Number Theory: A Very Short Introduction", author: "Robin Wilson", level: "intro" },
      { title: "Ireland and Rosen: A Classical Introduction to Modern Number Theory", author: "Kenneth Ireland, Michael Rosen", level: "advanced" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },
  {
    id: "analytic-number-theory",
    title: "Analytic Number Theory",
    description: "Using methods of analysis to solve problems about the integers and the distribution of primes.",
    author: "Prof. Martin",
    color: "#f472b6",
    icon: "bar-chart",
    code: "NUM.2",
    category: "Pure Mathematics — Number Theory",
    motivation:
      "How are the prime numbers distributed among all integers? This deceptively simple question launched one of the most fertile branches of mathematics, deploying the heavy artillery of complex analysis and Fourier analysis against the integers. The Riemann Hypothesis — still unproved — sits at its heart, offering a million-dollar bounty for anyone who can settle it.",
    bibliography: JSON.stringify([
      { title: "Introduction to Analytic Number Theory", author: "Tom M. Apostol", level: "intermediate" },
      { title: "Multiplicative Number Theory I", author: "Hugh L. Montgomery, Robert C. Vaughan", level: "advanced" },
      { title: "The Distribution of Prime Numbers", author: "Dimitris Koukoulopoulos", level: "advanced" },
      { title: "Prime Obsession", author: "John Derbyshire", level: "intro" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Applied Mathematics — Dynamical Systems ─────────────────────────
  {
    id: "ode",
    title: "Ordinary Differential Equations",
    description: "Equations involving functions of one variable and their derivatives, modeling change over time.",
    author: "Prof. Garnier",
    color: "#fbbf24",
    icon: "activity",
    code: "DYN.1",
    category: "Applied Mathematics — Dynamical Systems",
    motivation:
      "Ordinary differential equations are the mathematical language of change. Population growth, radioactive decay, the motion of planets, the oscillation of springs — all are governed by ODEs. Learning to solve and analyze them gives you superpowers for modeling the real world, from biology to engineering to economics.",
    bibliography: JSON.stringify([
      { title: "Ordinary Differential Equations", author: "Morris Tenenbaum, Harry Pollard", level: "intro" },
      { title: "Ordinary Differential Equations", author: "Vladimir I. Arnold", level: "intermediate" },
      { title: "Nonlinear Dynamics and Chaos", author: "Steven H. Strogatz", level: "intermediate" },
      { title: "Differential Equations and Dynamical Systems", author: "Lawrence Perko", level: "advanced" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },
  {
    id: "pde",
    title: "Partial Differential Equations",
    description: "Equations involving multivariable functions and their partial derivatives, describing heat, waves, and flow.",
    author: "Prof. Garnier",
    color: "#f59e0b",
    icon: "wind",
    code: "DYN.2",
    category: "Applied Mathematics — Dynamical Systems",
    motivation:
      "If ODEs model change in one dimension, PDEs model change across space and time simultaneously. The heat equation, the wave equation, the Navier-Stokes equations of fluid dynamics — these are all PDEs. Mastering them places you at the frontier where pure mathematics meets physics and engineering head-on.",
    bibliography: JSON.stringify([
      { title: "Partial Differential Equations: An Introduction", author: "Walter A. Strauss", level: "intro" },
      { title: "Partial Differential Equations", author: "Lawrence C. Evans", level: "advanced" },
      { title: "Partial Differential Equations in Action", author: "Sandro Salsa", level: "intermediate" },
      { title: "Applied Partial Differential Equations", author: "Richard Haberman", level: "intermediate" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Applied Mathematics — Mathematical Physics ──────────────────────
  {
    id: "mathematical-physics",
    title: "Mathematical Physics",
    description: "The rigorous mathematical frameworks underlying physical theories, from mechanics to quantum fields.",
    author: "Prof. Brun",
    color: "#e879f9",
    icon: "zap",
    code: "PHY.1",
    category: "Applied Mathematics — Mathematical Physics",
    motivation:
      "Physics asks the questions; mathematics provides the answers — and often, the questions that physics didn't know to ask. Mathematical physics is the grand arena where geometry, analysis, and algebra converge to describe the fundamental laws of nature. From symplectic geometry in classical mechanics to operator algebras in quantum theory, this is applied mathematics at its most profound.",
    bibliography: JSON.stringify([
      { title: "Mathematical Methods of Classical Mechanics", author: "Vladimir I. Arnold", level: "intermediate" },
      { title: "The Road to Reality", author: "Roger Penrose", level: "advanced" },
      { title: "Mathematics of Classical and Quantum Physics", author: "Frederick W. Byron, Robert W. Fuller", level: "intermediate" },
      { title: "Topology, Geometry and Gauge Fields", author: "Gregory L. Naber", level: "advanced" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Applied Mathematics — Theory of Computation ─────────────────────
  {
    id: "theory-of-computation",
    title: "Theory of Computation",
    description: "Formal languages, automata, computability, and the fundamental limits of what machines can compute.",
    author: "Prof. Leclerc",
    color: "#22d3ee",
    icon: "terminal",
    code: "CSC.1",
    category: "Applied Mathematics — Theory of Computation",
    motivation:
      "What can a computer actually compute? Are there problems no algorithm can ever solve? The theory of computation answers these questions with mathematical precision, drawing on logic, algebra, and combinatorics. Understanding Turing machines, NP-completeness, and formal languages is essential for anyone who wants to grasp the true power — and limits — of computation.",
    bibliography: JSON.stringify([
      { title: "Introduction to the Theory of Computation", author: "Michael Sipser", level: "intro" },
      { title: "Computational Complexity: A Modern Approach", author: "Sanjeev Arora, Boaz Barak", level: "advanced" },
      { title: "Introduction to Automata Theory, Languages, and Computation", author: "John E. Hopcroft, Jeffrey D. Ullman", level: "intermediate" },
      { title: "The Annotated Turing", author: "Charles Petzold", level: "intro" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Applied Mathematics — Information Theory ────────────────────────
  {
    id: "information-theory",
    title: "Information Theory",
    description: "The mathematical quantification of information, entropy, and the limits of data compression and transmission.",
    author: "Prof. Faure",
    color: "#a3e635",
    icon: "radio",
    code: "INF.1",
    category: "Applied Mathematics — Information Theory",
    motivation:
      "Claude Shannon single-handedly created information theory in 1948, and the world has never been the same. Every time you stream a video, send a text message, or compress a file, Shannon's theorems are at work. This module reveals the elegant mathematics behind communication, showing that information itself can be measured, bounded, and optimized.",
    bibliography: JSON.stringify([
      { title: "Elements of Information Theory", author: "Thomas M. Cover, Joy A. Thomas", level: "intermediate" },
      { title: "Information Theory, Inference and Learning Algorithms", author: "David J.C. MacKay", level: "intermediate" },
      { title: "A Mathematical Theory of Communication", author: "Claude E. Shannon", level: "advanced" },
      { title: "Information: A Very Short Introduction", author: "Luciano Floridi", level: "intro" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Applied Mathematics — Probability and Statistics ────────────────
  {
    id: "probability",
    title: "Probability Theory",
    description: "The rigorous mathematical framework for quantifying uncertainty and random phenomena.",
    author: "Prof. Blanc",
    color: "#4ade80",
    icon: "dice",
    code: "PRB.1",
    category: "Applied Mathematics — Probability and Statistics",
    motivation:
      "Uncertainty is woven into the fabric of the world, and probability theory is our most powerful tool for reasoning about it. From the law of large numbers to martingales, from random walks to stochastic processes, probability provides the mathematical backbone for finance, machine learning, statistical physics, and far more. It is pure mathematics with immediate real-world bite.",
    bibliography: JSON.stringify([
      { title: "Probability and Random Processes", author: "Geoffrey Grimmett, David Stirzaker", level: "intermediate" },
      { title: "A First Course in Probability", author: "Sheldon Ross", level: "intro" },
      { title: "Probability: Theory and Examples", author: "Rick Durrett", level: "advanced" },
      { title: "Introduction to Probability Models", author: "Sheldon Ross", level: "intermediate" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },
  {
    id: "statistics",
    title: "Statistics",
    description: "Methods for collecting, analyzing, and drawing conclusions from data under uncertainty.",
    author: "Prof. Blanc",
    color: "#86efac",
    icon: "pie-chart",
    code: "PRB.2",
    category: "Applied Mathematics — Probability and Statistics",
    motivation:
      "In a world drowning in data, statistics is the discipline that teaches you to separate signal from noise. Hypothesis testing, regression, Bayesian inference — these are not just academic exercises, they are the tools that drive medical trials, public policy, and scientific discovery. Understanding statistics deeply means you will never be misled by a misleading graph again.",
    bibliography: JSON.stringify([
      { title: "All of Statistics", author: "Larry Wasserman", level: "intermediate" },
      { title: "Statistical Inference", author: "George Casella, Roger L. Berger", level: "advanced" },
      { title: "The Art of Statistics", author: "David Spiegelhalter", level: "intro" },
      { title: "Computer Age Statistical Inference", author: "Bradley Efron, Trevor Hastie", level: "advanced" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Applied Mathematics — Game Theory ───────────────────────────────
  {
    id: "game-theory",
    title: "Game Theory",
    description: "Mathematical modeling of strategic interaction between rational decision-makers.",
    author: "Prof. Renard",
    color: "#f87171",
    icon: "users",
    code: "GAM.1",
    category: "Applied Mathematics — Game Theory",
    motivation:
      "Whenever two or more agents make decisions that affect each other — in economics, politics, biology, or even everyday negotiations — game theory provides the mathematical framework to analyze the outcome. From Nash equilibria to auction design, this is the mathematics of strategy, conflict, and cooperation. It won John Nash a Nobel Prize, and it will change how you see every human interaction.",
    bibliography: JSON.stringify([
      { title: "Game Theory: An Introduction", author: "Steven Tadelis", level: "intro" },
      { title: "A Course in Game Theory", author: "Martin J. Osborne, Ariel Rubinstein", level: "intermediate" },
      { title: "Algorithmic Game Theory", author: "Noam Nisan et al.", level: "advanced" },
      { title: "The Joy of Game Theory", author: "Presh Talwalkar", level: "intro" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Applied Mathematics — Operations Research ───────────────────────
  {
    id: "operations-research",
    title: "Operations Research",
    description: "Optimization techniques for decision-making: linear programming, scheduling, and resource allocation.",
    author: "Prof. Collet",
    color: "#fb7185",
    icon: "settings",
    code: "OPR.1",
    category: "Applied Mathematics — Operations Research",
    motivation:
      "Operations research is mathematics with its sleeves rolled up. It asks: given limited resources, how do you make the best possible decision? From scheduling airline crews to optimizing supply chains to planning military logistics, OR deploys linear programming, integer programming, and network optimization to solve problems that matter in the real world, right now.",
    bibliography: JSON.stringify([
      { title: "Introduction to Linear Optimization", author: "Dimitris Bertsimas, John N. Tsitsiklis", level: "intermediate" },
      { title: "Operations Research: Applications and Algorithms", author: "Wayne L. Winston", level: "intro" },
      { title: "Convex Optimization", author: "Stephen Boyd, Lieven Vandenberghe", level: "advanced" },
      { title: "Integer Programming", author: "Laurence A. Wolsey", level: "advanced" },
    ]),
    isMeta: false,
    posX: 0,
    posY: 0,
  },

  // ── Meta-Skills ─────────────────────────────────────────────────────
  {
    id: "problem-solving",
    title: "Problem Solving",
    description: "General strategies and heuristics for tackling mathematical problems of all kinds.",
    author: "MathGraph Team",
    color: "#14b8a6",
    icon: "lightbulb",
    code: "META.1",
    category: "Meta-Skills",
    motivation:
      "Knowing theorems is not enough — you must learn to wield them. Problem solving is the art of navigating from a question to an answer when no recipe is given. Through carefully chosen problems and battle-tested strategies, this module trains your mathematical instincts so that when you face the unknown, you have a toolkit of approaches ready to deploy.",
    bibliography: JSON.stringify([
      { title: "How to Solve It", author: "George Polya", level: "intro" },
      { title: "Problem-Solving Through Recreational Mathematics", author: "Averbach, Chein", level: "intro" },
      { title: "The Art and Craft of Problem Solving", author: "Paul Zeitz", level: "intermediate" },
      { title: "Putnam and Beyond", author: "Razvan Gelca, Titu Andreescu", level: "advanced" },
    ]),
    isMeta: true,
    posX: 0,
    posY: 0,
  },
  {
    id: "history-of-math",
    title: "History of Mathematics",
    description: "The evolution of mathematical ideas from antiquity to the modern era.",
    author: "MathGraph Team",
    color: "#d946ef",
    icon: "book-open",
    code: "META.2",
    category: "Meta-Skills",
    motivation:
      "Mathematics did not spring into existence fully formed — it was built by real people, across millennia, driven by curiosity, rivalry, and necessity. Understanding the history of mathematics enriches every theorem you learn: you see why the questions were asked, what wrong turns were taken, and how breakthroughs emerged. It transforms mathematics from a static collection of facts into a living, human story.",
    bibliography: JSON.stringify([
      { title: "A History of Mathematics", author: "Victor J. Katz", level: "intermediate" },
      { title: "Journey through Genius", author: "William Dunham", level: "intro" },
      { title: "Mathematics and Its History", author: "John Stillwell", level: "intermediate" },
      { title: "Men of Mathematics", author: "E.T. Bell", level: "intro" },
      { title: "The Princeton Companion to Mathematics", author: "Timothy Gowers et al.", level: "advanced" },
    ]),
    isMeta: true,
    posX: 0,
    posY: 0,
  },
  {
    id: "philosophy-of-math",
    title: "Philosophical Mathematics",
    description: "Foundational questions about the nature, truth, and meaning of mathematics.",
    author: "MathGraph Team",
    color: "#c084fc",
    icon: "help-circle",
    code: "META.3",
    category: "Meta-Skills",
    motivation:
      "Do mathematical objects exist independently of the human mind, or are they our invention? What does it mean for a theorem to be true? The philosophy of mathematics grapples with these deep questions, examining the foundations on which the entire discipline rests. Whether you lean toward Platonism, formalism, or intuitionism, engaging with these ideas will sharpen your understanding of what mathematics really is.",
    bibliography: JSON.stringify([
      { title: "Thinking about Mathematics", author: "Stewart Shapiro", level: "intro" },
      { title: "Philosophy of Mathematics: Selected Readings", author: "Paul Benacerraf, Hilary Putnam", level: "advanced" },
      { title: "Introduction to the Philosophy of Mathematics", author: "Mark Colyvan", level: "intermediate" },
      { title: "What Is Mathematics, Really?", author: "Reuben Hersh", level: "intro" },
    ]),
    isMeta: true,
    posX: 0,
    posY: 0,
  },
  {
    id: "using-lean",
    title: "Using Lean",
    description: "Introduction to the Lean proof assistant for formalizing and verifying mathematical proofs.",
    author: "MathGraph Team",
    color: "#06b6d4",
    icon: "code",
    code: "META.4",
    category: "Meta-Skills",
    motivation:
      "Lean is a revolutionary proof assistant that lets you write mathematics a computer can verify, line by line. In an era where AI and formal verification are transforming how we do mathematics, learning Lean puts you at the cutting edge. It also deepens your understanding of logic and proof structure in a way that pen-and-paper work alone never can.",
    bibliography: JSON.stringify([
      { title: "Theorem Proving in Lean 4", author: "Jeremy Avigad et al.", level: "intro" },
      { title: "Mathematics in Lean", author: "Jeremy Avigad, Patrick Massot", level: "intermediate" },
      { title: "Functional Programming in Lean", author: "David Thrane Christiansen", level: "intermediate" },
      { title: "The Mechanics of Proof", author: "Heather Macbeth", level: "intro" },
    ]),
    isMeta: true,
    posX: 0,
    posY: 0,
  },
];
